    parameters:
        database_driver:    pdo_mysql
        database_host:      localhost
        database_name:      bibliometrsym
        database_user:      root
        database_password:  123456